# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CityGame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 239)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(22)
        self.labelTitle.setFont(font)
        self.labelTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.inputLine = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.inputLine.setFont(font)
        self.inputLine.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.inputLine.setObjectName("inputLine")
        self.verticalLayout.addWidget(self.inputLine)
        self.layoutWithButtons = QtWidgets.QHBoxLayout()
        self.layoutWithButtons.setObjectName("layoutWithButtons")
        self.inputButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.inputButton.setFont(font)
        self.inputButton.setStyleSheet("background-color: rgb(250, 235, 180);")
        self.inputButton.setObjectName("inputButton")
        self.layoutWithButtons.addWidget(self.inputButton)
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.helpButton.setFont(font)
        self.helpButton.setStyleSheet("background-color: rgb(250, 235, 180);")
        self.helpButton.setObjectName("helpButton")
        self.layoutWithButtons.addWidget(self.helpButton)
        self.verticalLayout.addLayout(self.layoutWithButtons)
        self.labelProgramme = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        self.labelProgramme.setFont(font)
        self.labelProgramme.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProgramme.setObjectName("labelProgramme")
        self.verticalLayout.addWidget(self.labelProgramme)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 488, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "Что-то вроде игры в города..."))
        self.inputButton.setText(_translate("MainWindow", "Ввод"))
        self.helpButton.setText(_translate("MainWindow", "Подсказка"))
        self.labelProgramme.setText(_translate("MainWindow", "Я даю тебе фору,начинай!"))

